# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160805_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add',
        ),
    ]
