# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
            ],
            options={
                'verbose_name': '\u76ee\u5f551',
                'verbose_name_plural': '\u76ee\u5f55',
            },
        ),
    ]
