# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_addform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('autoid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('comtype', models.CharField(max_length=20)),
                ('catname', models.CharField(max_length=150)),
            ],
        ),
    ]
