# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160805_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='item',
        ),
        migrations.DeleteModel(
            name='add',
        ),
    ]
