# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160808_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe4\xb9\xa6\xe5\x90\x8d')),
                ('date', models.DateField(verbose_name=b'\xe5\x87\xba\xe7\x89\x88\xe6\x97\xb6\xe9\x97\xb4')),
                ('number', models.CharField(max_length=10, verbose_name=b'\xe6\x95\xb0\xe9\x87\x8f')),
            ],
            options={
                'verbose_name': '\u56fe\u4e66\u5217\u8868',
                'verbose_name_plural': '\u56fe\u4e66\u5217\u8868',
            },
        ),
    ]
