# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160215_0726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
