# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_examinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userForm',
        ),
    ]
