# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_loginuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='password',
            new_name='yourname',
        ),
        migrations.RenameField(
            model_name='loginuser',
            old_name='username',
            new_name='yourpassword',
        ),
    ]
