# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20160222_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
