# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160222_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('imageDetail', models.ImageField(upload_to=b'photos')),
            ],
        ),
    ]
