# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20160223_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='level',
            field=models.ImageField(upload_to=b'photos'),
        ),
    ]
