# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20160229_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='level',
            field=models.CharField(max_length=2),
        ),
    ]
