# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20160229_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='level',
            field=models.TextField(),
        ),
    ]
