# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'verbose_name': '\u76ee\u5f551', 'verbose_name_plural': '\u76ee\u5f55'},
        ),
        migrations.RemoveField(
            model_name='add',
            name='bz1',
        ),
        migrations.RemoveField(
            model_name='add',
            name='fj1',
        ),
        migrations.RemoveField(
            model_name='add',
            name='gjz1',
        ),
        migrations.RemoveField(
            model_name='add',
            name='headImg1',
        ),
        migrations.RemoveField(
            model_name='add',
            name='kid1',
        ),
        migrations.RemoveField(
            model_name='add',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='add',
            name='num',
        ),
        migrations.RemoveField(
            model_name='add',
            name='status1',
        ),
        migrations.RemoveField(
            model_name='add',
            name='where1',
        ),
        migrations.AddField(
            model_name='add',
            name='number',
            field=models.CharField(default=1, max_length=30, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d'),
            preserve_default=False,
        ),
    ]
