# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='add',
            name='number',
        ),
        migrations.AddField(
            model_name='add',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='add',
            name='image',
            field=models.ImageField(default=1, upload_to=b'photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add',
            name='item',
            field=models.ForeignKey(default=1.7, on_delete=django.db.models.deletion.CASCADE, to='polls.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add',
            name='title',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
    ]
