# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160805_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={},
        ),
    ]
